# Yazi configuration file

[mgr]
# Layout
linemode = "size_and_mtime"
show_hidden = false
show_symlink = true

# Sort method
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = true

# Column ratios
ratios = [1, 3, 4]

[preview]
# Tab size for text preview
tab_size = 2

# The filter used on image downscaling
image_filter = "catmull-rom"

# Quality on pre-caching images
image_quality = 90

[opener]
play = [
    { run = 'mpv "$@"', orphan = true, for = "unix" },
]
edit = [
    { run = 'micro "$@"', block = true, for = "unix" },
]
image = [
    { run = 'qimgv "$@"', orphan = true, for = "unix" },
]
open = [
    { run = 'xdg-open "$@"', desc = "Open" },
]

[open]
rules = [
    { mime = "text/*", use = "edit" },
    { mime = "image/*", use = "image" },
    { mime = "video/*", use = "play" },

    # { mime = "application/json", use = "edit" },
    { name = "*.json", use = "edit" },

    # Multiple openers for a single rule
    { name = "*.html", use = ["open", "edit"] },
    
    # Fallback
    { name = "*", use = "open" },
]

[tasks]
# Micro-mode settings
micro_workers = 5

# Macro-mode settings
macro_workers = 10

# Allow larger image allocation (e.g., for >10MB files that decompress to large bitmaps)
# 100MB = 104857600
image_alloc = 104857600
image_bound = [0, 0]

[plugin]
prepend_previewers = [
    { mime = "application/*zip", run = "archive" },
    { mime = "application/x-tar", run = "archive" },
    { mime = "application/x-bzip2", run = "archive" },
    { mime = "application/x-7z-compressed", run = "archive" },
    { mime = "application/x-rar", run = "archive" },
    { mime = "application/x-xz", run = "archive" },
]
