# Yazi configuration file

[mgr]
# Layout
linemode = "size_and_mtime"
show_hidden = false
show_symlink = true

# Sort method
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = true

# Column ratios
ratios = [1, 3, 4]

[preview]
# Tab size for text preview
tab_size = 2

# The filter used on image downscaling
image_filter = "catmull-rom"

# Quality on pre-caching images
image_quality = 90

[opener]
play = [
    { run = 'mpv "$@"', orphan = true, for = "unix" },
]
edit = [
    { run = '$EDITOR "$@"', block = true, for = "unix" },
]
open = [
    { run = 'xdg-open "$@"', desc = "Open" },
]

[open]
rules = [
    { mime = "text/*", use = "edit" },
    { mime = "video/*", use = "play" },

    # { mime = "application/json", use = "edit" },
    { name = "*.json", use = "edit" },

    # Multiple openers for a single rule
    { name = "*.html", use = ["open", "edit"] },
]

[tasks]
# Micro-mode settings
micro_workers = 5

# Macro-mode settings
macro_workers = 10
