[project]
name = "dotarch"
version = "0.1.0"
description = ""
requires-python = ">=3.11"
dependencies = [
    "ansible-lint>=25.9.2",
    "molecule==25.1.0",
    "molecule-plugins[vagrant]>=25.8.12",
    "yamllint>=1.37.1",
    "ansible>=12.2.0",
]
