---
# Handlers for common role

- name: restart greetd
  ansible.builtin.service:
    name: greetd
    state: restarted
  become: true

- name: restart waybar
  ansible.builtin.command: pkill -SIGUSR2 waybar
  ignore_errors: true
  become: true
