---
# Tasks for setting up Hyprland environment variables

- name: Create user environment directory
  file:
    path: "{{ ansible_facts['env'].HOME }}/.config/environment.d"
    state: directory
    mode: '0755'
  tags: [ wm, hyprland, environment ]

- name: Install user-specific environment variables
  template:
    src: home/.config/environment.d/user-env.conf.j2
    dest: "{{ ansible_facts['env'].HOME }}/.config/environment.d/user-env.conf"
    mode: '0644'
  tags: [ wm, hyprland, environment ]
