$ANSIBLE_VAULT;1.1;AES256
37383764383134353265353865643464386537316330636465373164326166626430373565316266
3962633761353837633835393366393636626330616136340a316566363063633230396331623334
64623261303565386366353962323262623335666232616238646239643465346265366339376238
3636623636376333340a653839353465623831373737623236663163333931653231373063653034
66333663623338663233333937626566653166393432313838313064376134663232656630623964
31356362643361383265313532626239313539383466643261653435363861343663373335363165
666461616464633966306135383232303639
