---
- name: Install necessary packages
  action:
    module: "{{ package_manager_module }}"
    name: "{{ bluetooth_packages }}"
    state: present
  become: yes

- name: Set Bluetooth auto-enable
  lineinfile:
    path: /etc/bluetooth/main.conf
    regexp: '^#?AutoEnable=true'
    line: 'AutoEnable=true'
    backrefs: yes
    state: present
  become: yes

- name: Enable bluetooth service to activate bluetooth on boot
  systemd:
    name: bluetooth.service
    enabled: yes
    state: started
  become: yes

- name: Install bluetuith (AUR)
  ansible.builtin.shell: 'yay -Sy --noconfirm bluetuith'
  become: yes
  become_user: '{{ username }}'
  tags: [ system, bluetooth ]
