---
- name: Install necessary packages
  community.general.pacman:
    name:
      - bluez-utils
      - bluez
      - bluez-obex
    state: present
  become: true

- name: Set Bluetooth auto-enable
  lineinfile:
    path: /etc/bluetooth/main.conf
    regexp: '^#?AutoEnable=true'
    line: 'AutoEnable=true'
    backrefs: yes
    state: present
  become: true

- name: Enable bluetooth service to activate bluetooth on boot
  systemd:
    name: bluetooth.service
    enabled: yes
    state: started
  become: true

- name: Install bluetuith (AUR)
  ansible.builtin.shell: 'yay -Sy --noconfirm bluetuith'
  become: true
  become_user: '{{ ansible_user }}'
  tags: [ system, bluetooth ]
