---
# Base system packages - core system components

- name: Install base system packages (Arch)
  become: true
  community.general.pacman:
    name:
      - btop
      - cifs-utils
      - ldns # Provide drill command
      - man-db
      - pacman-contrib
      - resolvconf # Required for WireGuard DNS management
      - rsync
      - socat
      - usbutils
      - wget
      - progress
      - atool
      - zip
      - unzip
      - 7zip
      - unrar
      - brightnessctl
      - reflector
      - jq
    state: present
  when: ansible_facts.distribution == 'Archlinux'
  tags: [ system ]

- name: Install system tools with yay (Arch)
  ansible.builtin.shell: 'yay -Sy --noconfirm {{ item }}'
  become: yes
  become_user: '{{ ansible_user }}'
  loop:
    - dasel-bin
  when: ansible_facts.distribution == 'Archlinux'
  tags: [ system ]

