---
- name: Check if yay is installed
  command: which yay
  register: yay_check
  ignore_errors: true
  changed_when: false

- name: Ensure base-devel and git are installed
  pacman:
    name:
      - base-devel
      - git
      - go
    state: present
  become: yes
  when: yay_check.rc != 0

- name: Clone yay from AUR
  git:
    repo: 'https://aur.archlinux.org/yay.git'
    dest: '{{ ansible_user_dir }}/yay'
    clone: yes
    update: yes
  when: yay_check.rc != 0

- name: Install yay
  command:
    cmd: makepkg -si --noconfirm
    chdir: '{{ ansible_user_dir }}/yay'
  become: yes
  become_user: '{{ ansible_user }}'
  when: yay_check.rc != 0

- name: Remove cloned directory
  file:
    path: "{{ ansible_user_dir }}/yay"
    state: absent
