---
- name: Install zathura (Arch)
  become: true
  community.general.pacman:
    name:
      - zathura
      - zathura-pdf-poppler
    state: present
  when: ansible_facts.distribution == 'Archlinux'
  tags: [ apps, zathura ]

- name: Install zathura (Ubuntu)
  become: true
  ansible.builtin.apt:
    name:
      - zathura
      - zathura-pdf-poppler
    state: present
    update_cache: true
  when: ansible_facts.distribution == 'Ubuntu'
  tags: [ apps, zathura ]

- name: Create zathura config directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/zathura"
    state: directory
    mode: '0755'
  tags: [ apps, zathura, config ]

- name: Copy Zathura configuration
  ansible.builtin.copy:
    src: files/home/.config/zathura/zathurarc
    dest: "{{ ansible_user_dir }}/.config/zathura/zathurarc"
    mode: '0644'
  tags: [ apps, zathura, config ]
