---
# Tasks for Yazi file manager configuration

-   name: Install Yazi file manager
    package:
        name: yazi
        state: present
    become: yes
    tags: [ wm, hyprland, yazi ]

-   name: Ensure yazi config directory exists
    file:
        path: '/home/{{ username }}/.config/yazi'
        state: directory
        mode: '0755'
    tags: [ wm, hyprland, yazi, config, directory ]

-   name: Sync yazi configuration files
    synchronize:
        src: 'home/.config/yazi/'
        dest: '/home/{{ username }}/.config/yazi/'
    tags: [ wm, hyprland, yazi, config, file ]
    become: yes
    become_user: '{{ username }}'
