---
# Desktop Rofi role - application launcher configuration
# This role manages Rofi application launcher setup

- name: Install Rofi
  become: true
  community.general.pacman:
    name: rofi
    state: present
  tags: [ desktop, rofi, package ]

- name: Create Rofi config directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/rofi"
    state: directory
    mode: '0755'
  tags: [ desktop, rofi, config ]

- name: Copy Rofi configurations
  ansible.builtin.copy:
    src: "files/home/.config/rofi/{{ item }}"
    dest: "{{ ansible_user_dir }}/.config/rofi/{{ item }}"
    mode: '0644'
  loop:
    - config.rasi
    - onedark.rasi
    - spotlight-custom.rasi
  tags: [ desktop, rofi, config ]