---
- include_tasks: system/main.yml
  tags: [ system, zsh ]

- include_tasks: wm-wayland/main.yml
  tags: [ wm, hyprland ]

- include_tasks: app/main.yml

- include_tasks: maintenance/main.yml
  tags: [ maintenance ]
